language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt -r requirements-dev.txt
env:
  global:
  - PYPI_USER_NAME: chaostoolkit
  - secure: SyPVscHmDPkUvOighC0wmAvx0Xz8DDy77JlPaY9T4508eFZOHJDyOICcNnylpg5q618+85LGOMQyNNigD9TxLje1gWBgHXJk5Eqs1PlRNba1xzMhHVnq2arFWdOVOqXe/zJTV8gNxBrtbNUp0rNWfMNX1IeqCarZkD71hG7XNgnCe3iyb5L9OboB1GwUmHVJDHYTE14n4WhUVk5vXgerT7GpKbXIEa5xb7wtnJg3dstWKdf1bnyvi3enzgh4nhk4YeRCgxR5t6DlYb1JgJEVSvN/JQNREenOcH5IrfxiUKJPAKXOXBGXP2Qpu6Uzr3vo5rKsUqZyPj2ySOU0B4H02qOSuxe3sFCjLGWcQTLp/g4K18p5uCurzrX2Z/V0KW0lF04g4PTMosqOWSlOZ0C8MqNNVAdZ30kq2LZPArf28VYPuquJlvw4G22vLmO0CQA7V/mQFFKy9VqHsWVKqhL8EzoFCeRDD6uZ7pxEv/g08GReJeq1dRK4qf+21Qz75+/e+hGlr3anJ21/RO5yF+cq+y3gw14h0iwjdTLdlMqHElZvyQn1whiFUfPsVtZhutPW2E5vzIQDrCECeWTH9KM104aQ9O4DtTeIk6Myf9tm7OeXXid/7Q2PyP4aRNB/7cioXBuWgtcY+iJKQ/3c28imelNmZbswM80SLVj5ONNwJBs=
script:
- bash ci.bash
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
